% function weather = weatherMap(location, varargin)


clear all
close all
clc

location = 'Hockenheim';


key = '3b335e249b442d0a31540c2a501141e1'; % Team key
options = weboptions('ContentType','json'); % Options DO NOT TOUCH
url = ['https://api.openweathermap.org/data/2.5/weather?q=', location,'&APPID=',key]; % API url
Current_Data = webread(url, options); % Need internet conection


fprintf('-----Weather report-----\n')
fprintf('Description: %s \n', Current_Data.weather.description)
fprintf('Current temp: %3.1f ºC \n', Current_Data.main.temp-273.15)
fprintf('Feeling: %3.1f ºC \n', Current_Data.main.feels_like-273.15)
fprintf('Max temp: %3.1f ºC \n', Current_Data.main.temp_max-273.15)
fprintf('Min temp: %3.1f ºC \n', Current_Data.main.temp_min-273.15)
fprintf('Pressure: %4.0f mbar \n', Current_Data.main.pressure)
fprintf('Humidity: %2.0f %% \n', Current_Data.main.humidity)
fprintf('Wind speed: %2.1f m/s \n', Current_Data.wind.speed)

if isempty(Current_Data.wind.deg)
else
    fprintf('Wind dir: %3.0f º \n', Current_Data.wind.deg)
end

% pause(1)

url = ['https://api.openweathermap.org/data/2.5/forecast?q=', location,'&APPID=',key]; % API url
Forecast = webread(url, options); % Need internet conection



Ndata = length(Forecast.list);

Time = cell(Ndata,1);
Temp = zeros(Ndata,1);
Temp_min = zeros(Ndata,1);
Temp_max = zeros(Ndata,1);
Feeling = zeros(Ndata,1);
Pressure = zeros(Ndata,1);
Humidity = zeros(Ndata,1);
Wind_speed = zeros(Ndata,1);
Wind_deg = zeros(Ndata,1);

for i = 1:Ndata
    Time{i} = Forecast.list{i,1}.dt_txt;
    Temp(i) = Forecast.list{1,1}.main.temp;
    Temp_min(i) = Forecast.list{1,1}.main.temp_min;
    Temp_max(i) = Forecast.list{1,1}.main.temp_max;
    Feeling(i) = Forecast.list{1,1}.main.feels_like;
    Pressure(i) = Forecast.list{1,1}.main.pressure;
    Humidity(i) = Forecast.list{1,1}.main.humidity;
    Wind_speed(i) = Forecast.list{1,1}.wind.speed;
    Wind_deg(i) = Forecast.list{1,1}.wind.deg;
end

Time = datetime(Time);
Temp = Temp - 273.15;
Temp_min = Temp_min - 273.15;
Temp_max = Temp_max - 273.15;

TT = timetable(Time,Temp,Temp_min,Temp_max,Feeling,Pressure,Humidity,Wind_speed,Wind_deg);

fprintf('\n\n')

disp(TT)


% Time = datetime({Forecast.list{1,1}.dt_txt; Forecast.list{2,1}.dt_txt; Forecast.list{3,1}.dt_txt; Forecast.list{4,1}.dt_txt;...
%     Forecast.list{5,1}.dt_txt; Forecast.list{6,1}.dt_txt; Forecast.list{7,1}.dt_txt; Forecast.list{8,1}.dt_txt;...
%     Forecast.list{9,1}.dt_txt; Forecast.list{10,1}.dt_txt; Forecast.list{11,1}.dt_txt; Forecast.list{12,1}.dt_txt;...
%     Forecast.list{13,1}.dt_txt; Forecast.list{14,1}.dt_txt; Forecast.list{15,1}.dt_txt; Forecast.list{16,1}.dt_txt;...
%     Forecast.list{17,1}.dt_txt; Forecast.list{18,1}.dt_txt; Forecast.list{19,1}.dt_txt; Forecast.list{20,1}.dt_txt;
%     Forecast.list{21,1}.dt_txt; Forecast.list{22,1}.dt_txt; Forecast.list{23,1}.dt_txt; Forecast.list{24,1}.dt_txt;
%     Forecast.list{25,1}.dt_txt; Forecast.list{26,1}.dt_txt; Forecast.list{27,1}.dt_txt; Forecast.list{28,1}.dt_txt;
%     Forecast.list{29,1}.dt_txt; Forecast.list{30,1}.dt_txt; Forecast.list{31,1}.dt_txt; Forecast.list{32,1}.dt_txt;
%     Forecast.list{33,1}.dt_txt; Forecast.list{34,1}.dt_txt; Forecast.list{35,1}.dt_txt; Forecast.list{36,1}.dt_txt;
%     Forecast.list{37,1}.dt_txt; Forecast.list{38,1}.dt_txt; Forecast.list{39,1}.dt_txt; Forecast.list{40,1}.dt_txt;});
% 
% Temp = [Forecast.list{1,1}.main.temp; Forecast.list{2,1}.main.temp; Forecast.list{3,1}.main.temp; Forecast.list{4,1}.main.temp; ...
%     Forecast.list{5,1}.main.temp; Forecast.list{6,1}.main.temp; Forecast.list{7,1}.main.temp; Forecast.list{8,1}.main.temp; ...
%     Forecast.list{9,1}.main.temp; Forecast.list{10,1}.main.temp; Forecast.list{11,1}.main.temp; Forecast.list{12,1}.main.temp; ...
%     Forecast.list{13,1}.main.temp; Forecast.list{14,1}.main.temp; Forecast.list{15,1}.main.temp; Forecast.list{16,1}.main.temp; ...
%     Forecast.list{17,1}.main.temp; Forecast.list{18,1}.main.temp; Forecast.list{19,1}.main.temp; Forecast.list{20,1}.main.temp; ...
%     Forecast.list{21,1}.main.temp; Forecast.list{22,1}.main.temp; Forecast.list{23,1}.main.temp; Forecast.list{24,1}.main.temp; ...
%     Forecast.list{25,1}.main.temp; Forecast.list{26,1}.main.temp; Forecast.list{27,1}.main.temp; Forecast.list{28,1}.main.temp; ...
%     Forecast.list{29,1}.main.temp; Forecast.list{30,1}.main.temp; Forecast.list{31,1}.main.temp; Forecast.list{32,1}.main.temp; ...
%     Forecast.list{33,1}.main.temp; Forecast.list{34,1}.main.temp; Forecast.list{35,1}.main.temp; Forecast.list{36,1}.main.temp; ...
%     Forecast.list{37,1}.main.temp; Forecast.list{38,1}.main.temp; Forecast.list{39,1}.main.temp; Forecast.list{40,1}.main.temp;];
% Temp = Temp - 273.15;
% 
% Temp_min = [Forecast.list{1,1}.main.temp_min; Forecast.list{2,1}.main.temp_min; Forecast.list{3,1}.main.temp_min; Forecast.list{4,1}.main.temp_min; ...
%     Forecast.list{5,1}.main.temp_min; Forecast.list{6,1}.main.temp_min; Forecast.list{7,1}.main.temp_min; Forecast.list{8,1}.main.temp_min; ...
%     Forecast.list{9,1}.main.temp_min; Forecast.list{10,1}.main.temp_min; Forecast.list{11,1}.main.temp_min; Forecast.list{12,1}.main.temp_min; ...
%     Forecast.list{13,1}.main.temp_min; Forecast.list{14,1}.main.temp_min; Forecast.list{15,1}.main.temp_min; Forecast.list{16,1}.main.temp_min; ...
%     Forecast.list{17,1}.main.temp_min; Forecast.list{18,1}.main.temp_min; Forecast.list{19,1}.main.temp_min; Forecast.list{20,1}.main.temp_min; ...
%     Forecast.list{21,1}.main.temp_min; Forecast.list{22,1}.main.temp_min; Forecast.list{23,1}.main.temp_min; Forecast.list{24,1}.main.temp_min; ...
%     Forecast.list{25,1}.main.temp_min; Forecast.list{26,1}.main.temp_min; Forecast.list{27,1}.main.temp_min; Forecast.list{28,1}.main.temp_min; ...
%     Forecast.list{29,1}.main.temp_min; Forecast.list{30,1}.main.temp_min; Forecast.list{31,1}.main.temp_min; Forecast.list{32,1}.main.temp_min; ...
%     Forecast.list{33,1}.main.temp_min; Forecast.list{34,1}.main.temp_min; Forecast.list{35,1}.main.temp_min; Forecast.list{36,1}.main.temp_min; ...
%     Forecast.list{37,1}.main.temp_min; Forecast.list{38,1}.main.temp_min; Forecast.list{39,1}.main.temp_min; Forecast.list{40,1}.main.temp_min;];
% Temp_min = Temp_min - 273.15;
% 
% Temp_max = [Forecast.list{1,1}.main.temp_max; Forecast.list{2,1}.main.temp_max; Forecast.list{3,1}.main.temp_max; Forecast.list{4,1}.main.temp_max; ...
%     Forecast.list{5,1}.main.temp_max; Forecast.list{6,1}.main.temp_max; Forecast.list{7,1}.main.temp_max; Forecast.list{8,1}.main.temp_max; ...
%     Forecast.list{9,1}.main.temp_max; Forecast.list{10,1}.main.temp_max; Forecast.list{11,1}.main.temp_max; Forecast.list{12,1}.main.temp_max; ...
%     Forecast.list{13,1}.main.temp_max; Forecast.list{14,1}.main.temp_max; Forecast.list{15,1}.main.temp_max; Forecast.list{16,1}.main.temp_max; ...
%     Forecast.list{17,1}.main.temp_max; Forecast.list{18,1}.main.temp_max; Forecast.list{19,1}.main.temp_max; Forecast.list{20,1}.main.temp_max; ...
%     Forecast.list{21,1}.main.temp_max; Forecast.list{22,1}.main.temp_max; Forecast.list{23,1}.main.temp_max; Forecast.list{24,1}.main.temp_max; ...
%     Forecast.list{25,1}.main.temp_max; Forecast.list{26,1}.main.temp_max; Forecast.list{27,1}.main.temp_max; Forecast.list{28,1}.main.temp_max; ...
%     Forecast.list{29,1}.main.temp_max; Forecast.list{30,1}.main.temp_max; Forecast.list{31,1}.main.temp_max; Forecast.list{32,1}.main.temp_max; ...
%     Forecast.list{33,1}.main.temp_max; Forecast.list{34,1}.main.temp_max; Forecast.list{35,1}.main.temp_max; Forecast.list{36,1}.main.temp_max; ...
%     Forecast.list{37,1}.main.temp_max; Forecast.list{38,1}.main.temp_max; Forecast.list{39,1}.main.temp_max; Forecast.list{40,1}.main.temp_max;];
% Temp_max = Temp_max - 273.15;
% 
% 
% Feeling = [Forecast.list{1,1}.main.feels_like; Forecast.list{2,1}.main.feels_like; Forecast.list{3,1}.main.feels_like; Forecast.list{4,1}.main.feels_like; ...
%     Forecast.list{5,1}.main.feels_like; Forecast.list{6,1}.main.feels_like; Forecast.list{7,1}.main.feels_like; Forecast.list{8,1}.main.feels_like; ...
%     Forecast.list{9,1}.main.feels_like; Forecast.list{10,1}.main.feels_like; Forecast.list{11,1}.main.feels_like; Forecast.list{12,1}.main.feels_like; ...
%     Forecast.list{13,1}.main.feels_like; Forecast.list{14,1}.main.feels_like; Forecast.list{15,1}.main.feels_like; Forecast.list{16,1}.main.feels_like; ...
%     Forecast.list{17,1}.main.feels_like; Forecast.list{18,1}.main.feels_like; Forecast.list{19,1}.main.feels_like; Forecast.list{20,1}.main.feels_like; ...
%     Forecast.list{21,1}.main.feels_like; Forecast.list{22,1}.main.feels_like; Forecast.list{23,1}.main.feels_like; Forecast.list{24,1}.main.feels_like; ...
%     Forecast.list{25,1}.main.feels_like; Forecast.list{26,1}.main.feels_like; Forecast.list{27,1}.main.feels_like; Forecast.list{28,1}.main.feels_like; ...
%     Forecast.list{29,1}.main.feels_like; Forecast.list{30,1}.main.feels_like; Forecast.list{31,1}.main.feels_like; Forecast.list{32,1}.main.feels_like; ...
%     Forecast.list{33,1}.main.feels_like; Forecast.list{34,1}.main.feels_like; Forecast.list{35,1}.main.feels_like; Forecast.list{36,1}.main.feels_like; ...
%     Forecast.list{37,1}.main.feels_like; Forecast.list{38,1}.main.feels_like; Forecast.list{39,1}.main.feels_like; Forecast.list{40,1}.main.feels_like;];
% Feeling = Feeling- 273.15;
% 
% Pressure = [Forecast.list{1,1}.main.pressure; Forecast.list{2,1}.main.pressure; Forecast.list{3,1}.main.pressure; Forecast.list{4,1}.main.pressure; ...
%     Forecast.list{5,1}.main.pressure; Forecast.list{6,1}.main.pressure; Forecast.list{7,1}.main.pressure; Forecast.list{8,1}.main.pressure; ...
%     Forecast.list{9,1}.main.pressure; Forecast.list{10,1}.main.pressure; Forecast.list{11,1}.main.pressure; Forecast.list{12,1}.main.pressure; ...
%     Forecast.list{13,1}.main.pressure; Forecast.list{14,1}.main.pressure; Forecast.list{15,1}.main.pressure; Forecast.list{16,1}.main.pressure; ...
%     Forecast.list{17,1}.main.pressure; Forecast.list{18,1}.main.pressure; Forecast.list{19,1}.main.pressure; Forecast.list{20,1}.main.pressure; ...
%     Forecast.list{21,1}.main.pressure; Forecast.list{22,1}.main.pressure; Forecast.list{23,1}.main.pressure; Forecast.list{24,1}.main.pressure; ...
%     Forecast.list{25,1}.main.pressure; Forecast.list{26,1}.main.pressure; Forecast.list{27,1}.main.pressure; Forecast.list{28,1}.main.pressure; ...
%     Forecast.list{29,1}.main.pressure; Forecast.list{30,1}.main.pressure; Forecast.list{31,1}.main.pressure; Forecast.list{32,1}.main.pressure; ...
%     Forecast.list{33,1}.main.pressure; Forecast.list{34,1}.main.pressure; Forecast.list{35,1}.main.pressure; Forecast.list{36,1}.main.pressure; ...
%     Forecast.list{37,1}.main.pressure; Forecast.list{38,1}.main.pressure; Forecast.list{39,1}.main.pressure; Forecast.list{40,1}.main.pressure;];
% 
% Humidity = [Forecast.list{1,1}.main.humidity; Forecast.list{2,1}.main.humidity; Forecast.list{3,1}.main.humidity; Forecast.list{4,1}.main.humidity; ...
%     Forecast.list{5,1}.main.humidity; Forecast.list{6,1}.main.humidity; Forecast.list{7,1}.main.humidity; Forecast.list{8,1}.main.humidity; ...
%     Forecast.list{9,1}.main.humidity; Forecast.list{10,1}.main.humidity; Forecast.list{11,1}.main.humidity; Forecast.list{12,1}.main.humidity; ...
%     Forecast.list{13,1}.main.humidity; Forecast.list{14,1}.main.humidity; Forecast.list{15,1}.main.humidity; Forecast.list{16,1}.main.humidity; ...
%     Forecast.list{17,1}.main.humidity; Forecast.list{18,1}.main.humidity; Forecast.list{19,1}.main.humidity; Forecast.list{20,1}.main.humidity; ...
%     Forecast.list{21,1}.main.humidity; Forecast.list{22,1}.main.humidity; Forecast.list{23,1}.main.humidity; Forecast.list{24,1}.main.humidity; ...
%     Forecast.list{25,1}.main.humidity; Forecast.list{26,1}.main.humidity; Forecast.list{27,1}.main.humidity; Forecast.list{28,1}.main.humidity; ...
%     Forecast.list{29,1}.main.humidity; Forecast.list{30,1}.main.humidity; Forecast.list{31,1}.main.humidity; Forecast.list{32,1}.main.humidity; ...
%     Forecast.list{33,1}.main.humidity; Forecast.list{34,1}.main.humidity; Forecast.list{35,1}.main.humidity; Forecast.list{36,1}.main.humidity; ...
%     Forecast.list{37,1}.main.humidity; Forecast.list{38,1}.main.humidity; Forecast.list{39,1}.main.humidity; Forecast.list{40,1}.main.humidity;];
% 
% 
% Wind_speed = [Forecast.list{1,1}.wind.speed; Forecast.list{2,1}.wind.speed; Forecast.list{3,1}.wind.speed; Forecast.list{4,1}.wind.speed; ...
%     Forecast.list{5,1}.wind.speed; Forecast.list{6,1}.wind.speed; Forecast.list{7,1}.wind.speed; Forecast.list{8,1}.wind.speed; ...
%     Forecast.list{9,1}.wind.speed; Forecast.list{10,1}.wind.speed; Forecast.list{11,1}.wind.speed; Forecast.list{12,1}.wind.speed; ...
%     Forecast.list{13,1}.wind.speed; Forecast.list{14,1}.wind.speed; Forecast.list{15,1}.wind.speed; Forecast.list{16,1}.wind.speed; ...
%     Forecast.list{17,1}.wind.speed; Forecast.list{18,1}.wind.speed; Forecast.list{19,1}.wind.speed; Forecast.list{20,1}.wind.speed; ...
%     Forecast.list{21,1}.wind.speed; Forecast.list{22,1}.wind.speed; Forecast.list{23,1}.wind.speed; Forecast.list{24,1}.wind.speed; ...
%     Forecast.list{25,1}.wind.speed; Forecast.list{26,1}.wind.speed; Forecast.list{27,1}.wind.speed; Forecast.list{28,1}.wind.speed; ...
%     Forecast.list{29,1}.wind.speed; Forecast.list{30,1}.wind.speed; Forecast.list{31,1}.wind.speed; Forecast.list{32,1}.wind.speed; ...
%     Forecast.list{33,1}.wind.speed; Forecast.list{34,1}.wind.speed; Forecast.list{35,1}.wind.speed; Forecast.list{36,1}.wind.speed; ...
%     Forecast.list{37,1}.wind.speed; Forecast.list{38,1}.wind.speed; Forecast.list{39,1}.wind.speed; Forecast.list{40,1}.wind.speed;];
% 
% 
% Wind_deg = [Forecast.list{1,1}.wind.deg; Forecast.list{2,1}.wind.deg; Forecast.list{3,1}.wind.deg; Forecast.list{4,1}.wind.deg; ...
%     Forecast.list{5,1}.wind.deg; Forecast.list{6,1}.wind.deg; Forecast.list{7,1}.wind.deg; Forecast.list{8,1}.wind.deg; ...
%     Forecast.list{9,1}.wind.deg; Forecast.list{10,1}.wind.deg; Forecast.list{11,1}.wind.deg; Forecast.list{12,1}.wind.deg; ...
%     Forecast.list{13,1}.wind.deg; Forecast.list{14,1}.wind.deg; Forecast.list{15,1}.wind.deg; Forecast.list{16,1}.wind.deg; ...
%     Forecast.list{17,1}.wind.deg; Forecast.list{18,1}.wind.deg; Forecast.list{19,1}.wind.deg; Forecast.list{20,1}.wind.deg; ...
%     Forecast.list{21,1}.wind.deg; Forecast.list{22,1}.wind.deg; Forecast.list{23,1}.wind.deg; Forecast.list{24,1}.wind.deg; ...
%     Forecast.list{25,1}.wind.deg; Forecast.list{26,1}.wind.deg; Forecast.list{27,1}.wind.deg; Forecast.list{28,1}.wind.deg; ...
%     Forecast.list{29,1}.wind.deg; Forecast.list{30,1}.wind.deg; Forecast.list{31,1}.wind.deg; Forecast.list{32,1}.wind.deg; ...
%     Forecast.list{33,1}.wind.deg; Forecast.list{34,1}.wind.deg; Forecast.list{35,1}.wind.deg; Forecast.list{36,1}.wind.deg; ...
%     Forecast.list{37,1}.wind.deg; Forecast.list{38,1}.wind.deg; Forecast.list{39,1}.wind.deg; Forecast.list{40,1}.wind.deg;];
% 
% TT = timetable(Time,Temp,Temp_min,Temp_max,Feeling,Pressure,Humidity,Wind_speed,Wind_deg);
% 
% fprintf('--------------------------------------------------\n')
% 
% disp(TT)



